sbatch run_train_cifar100_ftrojan_sdd42_ours_moco_nodrop.slurm
sbatch run_train_cifar100_htba_sdd42_ours_moco_nodrop.slurm
sbatch run_train_cifar10_ftrojan_sdd42_ours_moco_nodrop.slurm
sbatch run_train_cifar10_htba_sdd42_ours_moco_nodrop.slurm
sbatch run_train_imagenet100_ftrojan_sdd42_ours_moco_nodrop.slurm
sbatch run_train_imagenet100_htba_sdd42_ours_moco_nodrop.slurm